resolver: lts-16.9
extra-package-dbs: []
packages:
- '.'
extra-deps:
- 'hakyll-4.13.4.1'
- 'pandoc-2.10.1'
- 'commonmark-0.1.1.2'
- 'commonmark-extensions-0.2.0.4'
- 'commonmark-pandoc-0.2.0.1'
- 'hslua-1.1.2'
- 'jira-wiki-markup-1.3.2'
- 'pandoc-types-1.21'
nix:
  packages: ["zlib.dev", "zlib.out"]
